---
title: "Sketch integration using SCTransform"
output: html_notebook
---

```{r setup, include=FALSE}
all_times <- list()  # store the time for each chunk
knitr::knit_hooks$set(time_it = local({
  now <- NULL
  function(before, options) {
    if (before) {
      now <<- Sys.time()
    } else {
      res <- difftime(Sys.time(), now, units = "secs")
      all_times[[options$label]] <<- res
    }
  }
}))
knitr::opts_chunk$set(
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 95),
  message = FALSE,
  warning = FALSE,
  time_it = TRUE,
  error = TRUE
)
```

## load package

```{r, warning=F, message=F}
library(Seurat)
library(BPCells)
library(dplyr)
```

## load matrix
```{r, warning=F, message=F}
 
time0_loadMatrix <- system.time({ 
  #mat <- open_matrix_dir('/brahms/haoy/test/pbmc_150k_sparse/')
  #meta <- readRDS('/brahms/haoy/seurat5/S5_object/ParseBio_PBMC_meta_100K.rds')
  mat <- open_matrix_dir('/brahms/haoy/test/pbmc_ParseBio_sparse//')
  meta <- readRDS('/brahms/haoy/seurat5/S5_object/ParseBio_PBMC_meta.rds')
  
})
```

## sketch object
```{r,warning=F, message=F}

options(Seurat.object.assay.version = "v5",   Seurat.object.assay.calcn = T)
time1_normalize <- system.time({
  object <- CreateSeuratObject(counts = mat, meta.data = meta)
  object <- NormalizeData(object)
  # object[['RNA']]$data <- write_matrix_dir(
  #   mat = object[['RNA']]$data,
  #   dir = '/brahms/haoy/test/pbmc_ParseBio_sparse_data'
  #   )
  #object[['RNA']]$data <- open_matrix_dir(dir = '/brahms/haoy/test/pbmc_ParseBio_sparse_data')
})
 

time2_split.mat  <- system.time({
  options(Seurat.object.assay.calcn = FALSE) 
  object[['RNA']] <- split(object[['RNA']], f =  meta$sample)
})


time3_FindVariable  <- system.time({
  object <- FindVariableFeatures(object, layer = 'counts')
}
)

time4_LeverageScoreSampling  <- system.time({
  object <- LeverageScore(object)
  object <- LeverageScoreSampling(object = object, ncells = 5000, cast = 'dgCMatrix')
})

```

## integrate sketched assay
```{r}

time5_SketchIntegration  <- system.time({
  DefaultAssay(object) <- 'sketch'
  object <- SCTransform(object)
  object <- RunPCA(object,  verbose = F)
  features <-  rownames(object[['pca']][])
  DefaultAssay(object) <- 'SCT'
  options(future.globals.maxSize = 8e9)
  object <- IntegrateLayers(object, 
                            method = RPCAIntegration,
                            orig = 'pca', 
                            new.reduction = 'integrated.rpca',
                            normalization.method =  "SCT",
                            dims = 1:30, 
                            k.anchor = 20,
                            features = features,
                            reference = which(Layers(object[['sketch']], search = 'data') %in% c( 'data.H_3060')), 
                            verbose = F)
 
})
object <- RunUMAP(object,  reduction = 'integrated.rpca', dims = 1:30, return.model = T, verbose = F)
plot.s1 <- DimPlot(object, group.by = 'sample', reduction = 'umap') + NoLegend()
plot.s2 <- DimPlot(object, group.by = 'celltype.weight', reduction = 'umap') + NoLegend()
```
```{r}
plot.s1 + plot.s2

```


## proporgate embeddings to full data
```{r}
time6_UnSketch <- system.time({
  object <- IntegrateSketchEmbeddings(object = object,
                                       atoms = 'sketch',
                                       orig = 'RNA',
                                       reduction = 'integrated.rpca' ,
                                       layers = Layers(object = object[['RNA']], search = 'data'),
                                      features = features  )
 
})
 

```

```{r}
 object <- RunUMAP(object,  reduction = 'integrated.rpca.orig', dims = 1:30 , reduction.name = 'umap.orig', reduction.key = 'Uorig_')
```

## save object
```{r}
#time7_saveRDS <- system.time(saveRDS(object, "/brahms/haoy/test/pbmc_ParseBio_seurat_SCT.rds"))
```

## pseudo-bulk
```{r}
time8_bulk <- system.time( bulk <- AverageExpression(object,
                                                        return.seurat = T,
                                                        slot = 'counts',
                                                        assays  = 'RNA',
                                                        group.by = c("celltype.weight","sample")
                                                        )
)
marker <- FindAllMarkers(object = bulk, only.pos = TRUE, verbose = FALSE)
marker %>%
    group_by(cluster) %>%
    top_n(n = -5, wt = p_val) -> top5
bulk <- ScaleData(bulk, features = top5$gene)

```

## computing time summary
```{r}
all_T  <- ls(pattern = 'time')
overall <- sum(sapply(all_T, function(x) round(get(x)['elapsed'], digits = 3)))/60


for (i in 1:length(all_T)) {
  T_i <- get(all_T[i])['elapsed']
  if (T_i > 60) {
     print(paste(all_T[i], round(T_i/60, digits = 1), 'mins'))
  } else {
     print(paste(all_T[i], round(T_i, digits = 1), 'secs'))
  }
}
print(paste('Total time ', round(overall, digits = 1), 'mins' ))
```


```{r}
object$disease <- sapply(strsplit(x = object$sample, split = "_"), '[', 1)

```
```{r}
p1<- DimPlot(object, reduction = 'umap.orig', group.by = 'sample',alpha = 0.1) + NoLegend()
p2<- DimPlot(object, reduction = 'umap.orig', group.by = 'celltype.weight', label = T, alpha = 0.1) + NoLegend()
p3<- DimPlot(object, reduction = 'umap.orig', group.by = 'disease', label = T, alpha = 0.1) + NoLegend()

p1+p2 + p3

```
```{r,fig.height = 20, fig.width = 15}
DoHeatmap(bulk, features = top5$gene) + NoLegend()

```
