---
title: "Map COVID PBMC datasets to a healthy reference"
output:
  html_document:
    theme: united
    df_print: kable
  pdf_document: default
date: 'Compiled: `r Sys.Date()`'
---

```{r setup, include=TRUE}
all_times <- list()  # store the time for each chunk
knitr::knit_hooks$set(time_it = local({
  now <- NULL
  function(before, options) {
    if (before) {
      now <<- Sys.time()
    } else {
      res <- difftime(Sys.time(), now, units = "secs")
      all_times[[options$label]] <<- res
    }
  }
}))
knitr::opts_chunk$set(
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 95),
  message = FALSE,
  warning = FALSE,
  fig.width = 10,
  time_it = TRUE,
  error = TRUE
)
```

## load package

```{r, warning=F, message=F}
library(Seurat)
library(BPCells)
library(dplyr)
```

## load matrix
```{r, warning=F, message=F}
time0_loadMatrix <- system.time({ 
  
file.dir <- "../data/PBMCVignette/"
files.set <- c("arunachalam_2020_processed.BPCells", "combes_2021_processed.BPCells", "lee_2020_processed.BPCells",
               "wilk_2020_processed.BPCells", "yao_2021_processed.BPCells")
meta.list <- readRDS('../data/PBMCVignette/PBMC_meta.list')
names(meta.list) <- gsub('_processed.BPCells','',files.set)

input.list <- list()
for (i in 1:length(files.set)) {
  input.list[[i]] <- open_matrix_dir(dir = paste0(file.dir, files.set[i]) )
  colnames(input.list[[i]]) <- paste0(names(meta.list)[i], "_",    colnames(input.list[[i]]))
  rownames(meta.list[[i]]) <-paste0(names(meta.list)[i], "_",  rownames(meta.list[[i]]))
  meta.list[[i]]$batch <- names(meta.list)[i]
  meta.list[[i]]$celltype <-   meta.list[[i]]$predicted.celltype.l2
  
}
 names(input.list) <- paste0('counts.',gsub('_processed.BPCells','',files.set))
  meta_data <- lapply(meta.list, function(x) {
    x <- x[,c('batch', 'celltype', 'patient', 'disease_status_standard' )]
    return(x)
  })
  meta_data <- Reduce(rbind, meta_data)
})
```

## load query
```{r,warning=F, message=F}

options(Seurat.object.assay.version = "v5",   Seurat.object.assay.calcn = T)
time1_normalize <- system.time({
 
  object <- CreateSeuratObject(counts = input.list[1:2], meta.data = meta_data)
  object <- NormalizeData(object, verbose = FALSE)
})

```

## load reference
```{r}
obj.ref <- readRDS("../data/pbmc_multimodal_2023.rds")
obj.ref 
```
## mapping
```{r}


time2_anchoring <- system.time({
anchor <- FindTransferAnchors(reference = obj.ref,
                              query = object, 
                              reference.reduction = 'spca', 
                              normalization.method = 'SCT',
                              dims = 1:50,
                              k.filter = NA, 
                              k.anchor = 5,
                              features = rownames(obj.ref[['spca']]@feature.loadings))
})

time3_MapQuery <- system.time({

  object <- MapQuery(
  anchorset = anchor,
  query = object,
  reference = obj.ref,
  refdata = list(
    l1.s5 = "celltype.l1",
    l2.s5 = "celltype.l2"
  ),
  reduction.model = "wnn.umap"
)
})

```
```{r}
anchor
```
 

```{r}
 p1<- DimPlot(object, reduction = 'ref.umap', group.by = 'predicted.l2.s5',alpha = 0.8, label = T) + NoLegend()
 p2<- DimPlot(object, reduction = 'ref.umap', group.by = 'celltype',alpha = 0.8, label = T) + NoLegend()

 p1+p2

```
```{r, fig.width=10, fig.height=10}
p3 <-DimPlot(object, reduction = 'ref.umap', group.by = 'celltype',alpha = 0.8, label = T, split.by = 'batch', ncol = 3) + NoLegend()
p3
```
 
## pseudo-bulk
```{r}

time4_bulk <- system.time( bulk <- AverageExpression(object,
                                                     method = 'aggregate',
                                                        return.seurat = T,
                                                        slot = 'counts',
                                                        assays  = 'RNA',
                                                        group.by = c("predicted.l2.s5","patient","disease_status_standard")
                                                        )
)

bulk$celltype <- sapply(strsplit(Cells(bulk), split = "_"), '[', 1)
bulk$donor <- sapply(strsplit(Cells(bulk), split = "_"), '[', 2)
bulk$disease <- sapply(strsplit(Cells(bulk), split = "_"), '[', 3)
bulk <- subset(bulk, subset = disease != 'other')

```

```{R}
marker.list <- list()
celltype.set <- unique(bulk$celltype )
for (i in seq_along(celltype.set)) {
  bulk.i <- subset(bulk, subset = celltype == celltype.set[i])
  Idents(bulk.i) <- 'disease'
 if (any(table(bulk.i$disease) < 3)) {
    marker.list[[i]]  <- EmptyDF(n = 0)
 } else {
    marker.list[[i]] <- FindMarkers(bulk.i, ident.1 = 'COVID-19',ident.2 = 'healthy', slot = 'counts', test.use = 'DESeq2', verbose = F )
 }
     
}
names(marker.list) <- celltype.set

```
```{r}
marker.list.filter <- lapply(marker.list, function(x) {
  if(nrow(x) > 0) {
    x <- x[x$p_val_adj < 0.01 & !is.na(x$p_val_adj ),]
  } 
  if (nrow(x) > 0) {
    return(x)
  }
})


```
```{r} 
bulk$disease <- factor(bulk$disease, levels = c('healthy', 'COVID-19'))

```

```{r, fig.width=10, fig.height=5}
VlnPlot(bulk, features = 'MX1', group.by = 'celltype', split.by = 'disease', cols = c("#377eb8", "#e41a1c"))
```
 
```{r save.img, include=TRUE}
library(ggplot2)
ggsave(filename = "../output/images/COVID_SCTMapping.jpg", height = 7, width = 8, plot = p3, quality = 50)
```

```{r save.times, include=TRUE}
print(as.data.frame(all_times))
write.csv(x = t(as.data.frame(all_times)), file = "../output/timings/COVID_SCTMapping.csv")
```

<details>
  <summary>**Session Info**</summary>
```{r}
sessionInfo()
```
</details>
