---
title: "Mouse brain sketch clustering"
output:
  html_document:
    theme: united
    df_print: kable
  pdf_document: default
date: 'Compiled: `r Sys.Date()`'
---

```{r setup, include=TRUE}
all_times <- list()  # store the time for each chunk
knitr::knit_hooks$set(time_it = local({
  now <- NULL
  function(before, options) {
    if (before) {
      now <<- Sys.time()
    } else {
      res <- difftime(Sys.time(), now, units = "secs")
      all_times[[options$label]] <<- res
    }
  }
}))
knitr::opts_chunk$set(
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 95),
  message = FALSE,
  warning = FALSE,
  fig.width = 10,
  time_it = TRUE,
  error = TRUE
)
```
 
## load library
```{r, warning=FALSE, message=FALSE}
library(Seurat)
library(BPCells)
```
 
## load data from h5ad 
```{r, warning=FALSE, message=FALSE}
t0_CreateObject <- system.time({

mat <- open_matrix_dir("../data/mouse_1M_neurons_counts")[,1:1e5]
 
mat <- Azimuth::ConvertEnsembleToSymbol(mat = mat, species = 'mouse')
 
options(Seurat.object.assay.version = "v5",  Seurat.object.assay.calcn = T)
obj <- CreateSeuratObject(counts = mat )
 
})

```

## create sketch assay
```{r, warning=FALSE, message=FALSE}
t1_CreateSketchAssay <- system.time({
obj <- NormalizeData(obj)
obj <- FindVariableFeatures(obj, layer = 'counts')
obj <- LeverageScoreSampling(object = obj, ncells = 5000, cast = 'dgCMatrix')
 
})

```
## Sketch assay clustering
```{r, warning=FALSE, message=FALSE}
t2_SketchClustering <- system.time({
obj <- FindVariableFeatures(obj)
obj <- ScaleData(obj)
obj <- RunPCA(obj)
obj <- FindNeighbors(obj, dims = 1:50)
obj <- FindClusters(obj)
})

obj <- RunUMAP(obj, dims = 1:50, return.model = T)
```

```{r}
DimPlot(obj, label = T, reduction = 'umap') + NoLegend() 
```


```{r}
DimPlot(obj, reduction = 'umap', label = T) + NoLegend()

```
```{r,fig.height = 20, fig.width = 15}
features.set <- c('Aqp4', 'Sox10', 'Slc17a7', 'Aif1', 'Foxj1', 'Pax6', 'Slc17a6', 'Lum', 'Nanog', 'Gad2', 'Foxj1',   'Cldn5','Alas2')
features.gaba.set <- c('Gad1','Mef2c','Sst','Lhx6','Nr2f2','Prox1') 
DefaultAssay(obj) <- 'sketch'
FeaturePlot(obj, reduction = 'umap', features = features.set, max.cutoff = "q99", min.cutoff = 'q1')
FeaturePlot(obj, reduction = 'umap', features = features.gaba.set, max.cutoff = "q99", min.cutoff = 'q1')

```

## Project full cells to PCA from sketch assay 
```{r, warning=FALSE, message=FALSE}
t3_ProjectEmbedding <- system.time({
  ref.emb <- ProjectCellEmbeddings(query = obj,
                                   reference = obj,
                                   query.assay = 'RNA',
                                   reference.assay = 'sketch',
                                                reduction = 'pca')
obj[['pca.orig']] <- CreateDimReducObject(embeddings = ref.emb, assay = 'RNA')
DefaultAssay(obj) <- 'RNA'
})



``` 

## Transfer labels and umap from sketch to full data
```{r, warning=FALSE, message=FALSE}
t4_transferLabel <- system.time({
   options(future.globals.maxSize = 1e9)
  obj <- TransferSketchLabels(object = obj,
                            atoms = 'sketch',
                            reduction = 'pca.orig',
                            dims = 1:50,
                            refdata = list(cluster_full = 'sketch_snn_res.0.8'),
                            reduction.model = 'umap'
                            )
})

```


```{r}
library(ggplot2)
DimPlot(obj, label = T, reduction = 'ref.umap', group.by = 'predicted.cluster_full', alpha = 0.1) + NoLegend()  

```

```{r}

obj[['pca.nn']] <- Seurat:::NNHelper(data = obj[['pca.orig']]@cell.embeddings[,1:50], 
                            k = 30, 
                            method = "hnsw", 
                            metric = "cosine", 
                            n_threads = 10)
obj <- RunUMAP(obj, nn.name = "pca.nn", reduction.name = 'umap.orig', reduction.key = 'Uo_')
 
```

```{r}
DimPlot(obj, label = T, reduction = 'umap.orig', group.by = 'predicted.cluster_full', alpha = 0.1) + NoLegend()  

```

## sub type clustering
```{r}
obj.sub <- subset(obj, subset = predicted.cluster_full %in% c(5, 12))
obj.sub[['sketch']] <- NULL
obj.sub[['RNA']] <- CastAssay(object = obj.sub[['RNA']], to = "dgCMatrix" )
obj.sub <- FindVariableFeatures(obj.sub, layer = 'counts')
obj.sub <- ScaleData(obj.sub)
obj.sub <- RunPCA(obj.sub)
obj.sub <- RunUMAP(obj.sub, dims = 1:30)
obj.sub <- FindNeighbors(obj.sub, dims = 1:30)
obj.sub <- FindClusters(obj.sub)
```

```{r}
p <- DimPlot(obj.sub, label = T) + NoLegend()
p
```

```{r save.img, include=TRUE}
library(ggplot2)
p <- DimPlot(obj, label = T, label.size=8, reduction = "ref.umap", group.by = "predicted.cluster_full", alpha = 0.1) + NoLegend()
ggsave(filename = "../output/images/MouseBrain_sketch_clustering.jpg", height = 7, width = 7, plot = p, quality = 50)
```

```{r save.times, include=TRUE}
print(as.data.frame(all_times))
write.csv(x = t(as.data.frame(all_times)), file = "../output/timings/MouseBrain_sketch_clustering.csv")
```

<details>
  <summary>**Session Info**</summary>
```{r}
sessionInfo()
```
</details>
