---
title: "Sketch integration using a 1 million cell dataset from Parse Biosciences"
output:
  html_document:
    theme: united
    df_print: kable
  pdf_document: default
date: 'Compiled: `r Sys.Date()`'
---

```{r setup, include=TRUE}
all_times <- list()  # store the time for each chunk
knitr::knit_hooks$set(time_it = local({
  now <- NULL
  function(before, options) {
    if (before) {
      now <<- Sys.time()
    } else {
      res <- difftime(Sys.time(), now, units = "secs")
      all_times[[options$label]] <<- res
    }
  }
}))
knitr::opts_chunk$set(
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 95),
  message = FALSE,
  warning = FALSE,
  fig.width = 10,
  time_it = TRUE,
  error = TRUE
)
```

## load package

```{r, warning=F, message=F}
library(Seurat)
library(BPCells)
library(dplyr)
```

## load matrix

```{r, warning=F, message=F}
time0_loadMatrix <- system.time({ 
  mat <- open_matrix_dir('../data/pbmc_150k_sparse/')
  meta <- readRDS('../data/ParseBio_PBMC_meta_100K.rds')
  meta$disease <- sample(c('H','D'), nrow(meta), replace = T)
})
```

## sketch object
```{r,warning=F, message=F}

options(Seurat.object.assay.version = "v5",   Seurat.object.assay.calcn = T)
time1_normalize <- system.time({
  object <- CreateSeuratObject(counts = mat, meta.data = meta)
  object <- NormalizeData(object, verbose = FALSE)
})
 

time2_split.mat  <- system.time({
  options(Seurat.object.assay.calcn = FALSE) 
  object[['RNA']] <- split(object[['RNA']], f =  object$sample)
})


time3_FindVariable  <- system.time({
  object <- FindVariableFeatures(object, layer = 'counts',  verbose = FALSE)
}
)

time4_LeverageScoreSampling  <- system.time({
  object <- LeverageScoreSampling(object = object, ncells = 5000, cast = 'dgCMatrix', verbose = FALSE)
})

```

## integrate sketched assay
```{r}

time5_SketchIntegration  <- system.time({
  DefaultAssay(object) <- 'sketch'
  object <- FindVariableFeatures(object, verbose = F, nfeatures = 2000)
  features <- VariableFeatures(object)
  object <- ScaleData(object, features =  features, verbose = F)
  object <- RunPCA(object, features =  features, verbose = F)
  DefaultAssay(object) <- 'sketch'
  options(future.globals.maxSize = 3e9)
  object <- IntegrateLayers(object,
                            method = RPCAIntegration,
                            orig = 'pca',
                            new.reduction = 'integrated.rpca',
                            dims = 1:30, 
                            k.anchor = 20,
                            reference = which(Layers(object, search = 'data') %in% c( 'data.H_3060')), 
                            verbose = F)
 
})
object <- RunUMAP(object,  reduction = 'integrated.rpca', dims = 1:30, return.model = T, verbose = F)
plot.s1 <- DimPlot(object, group.by = 'sample', reduction = 'umap') + NoLegend()
plot.s2 <- DimPlot(object, group.by = 'celltype.weight', reduction = 'umap') + NoLegend()
```
```{r}
plot.s1 + plot.s2

```


## proporgate embeddings to full data
```{r}
time6_UnSketch <- system.time({
  object <- IntegrateSketchEmbeddings(object = object,
                                       atoms = 'sketch',
                                       orig = 'RNA',
                                       reduction = 'integrated.rpca' ,
                                       layers = Layers(object = object[['RNA']], search = 'data'),
                                      features = features)
 
})
 

```

```{r}
object <- RunUMAP(object,  reduction = 'integrated.rpca.orig', dims = 1:30 , reduction.name = 'umap.orig', reduction.key = 'Uorig_')
```
```{r}
p1<- DimPlot(object, reduction = 'umap.orig', group.by = 'sample',alpha = 0.5) + NoLegend()
p2<- DimPlot(object, reduction = 'umap.orig', group.by = 'celltype.weight', label = T, alpha = 0.5) + NoLegend()
p1+p2

```

## pseudo-bulk
```{r}

time8_bulk <- system.time( bulk <- AggregateExpression(object,
                                                        return.seurat = T,
                                                        slot = 'counts',
                                                        assays  = 'RNA',
                                                        group.by = c("celltype.weight","sample","disease")
                                                        )
)

bulk$celltype <- sapply(strsplit(Cells(bulk), split = "_"), '[', 1)
bulk$donor <- sapply(strsplit(Cells(bulk), split = "_"), '[', 2)
bulk$disease <- sapply(strsplit(Cells(bulk), split = "_"), '[', 3)

marker.list <- list()
celltype.set <- unique(bulk$celltype )
for (i in seq_along(celltype.set)) {
  bulk.i <- subset(bulk, subset = celltype == celltype.set[i])
  Idents(bulk.i) <- 'disease'
 if (any(table(bulk.i$disease) < 3)) {
    marker.list[[i]]  <- EmptyDF(n = 0)
 } else {
    marker.list[[i]] <- FindMarkers(bulk.i, ident.1 = 'D',ident.2 = 'H', slot = 'counts', test.use = 'DESeq2', verbose = F )
 }
}
names(marker.list) <- celltype.set
```

```{r}
marker.list.filter <- lapply(marker.list, function(x) {
  if(nrow(x) > 0) {
    x <- x[x$p_val_adj < 0.01 & !is.na(x$p_val_adj ),]
  } 
  if (nrow(x) > 0) {
    return(x)
  }
})

```

```{r}
VlnPlot(bulk, features = 'FOXO3', group.by = 'celltype', split.by = 'disease')
```

```{r,fig.height = 20, fig.width = 15}
Idents(bulk) <- 'celltype'
marker <- FindAllMarkers(object = bulk, only.pos = TRUE, verbose = FALSE)
marker %>%
    group_by(cluster) %>%
    top_n(n = -5, wt = p_val) -> top5
bulk <- ScaleData(bulk, features = top5$gene)
DoHeatmap(bulk, features = top5$gene) + NoLegend()
```

```{r save.img, include=TRUE}
library(ggplot2)
plot <- DoHeatmap(bulk, features = top5$gene) + NoLegend()
ggsave(filename = "../output/images/ParseBio_sketch_integration.jpg", height = 10, width = 7, plot = plot, quality = 50)
```

```{r save.times, include=TRUE}
print(as.data.frame(all_times))
write.csv(x = t(as.data.frame(all_times)), file = "../output/timings/ParseBio_sketch_integration.csv")
```

<details>
  <summary>**Session Info**</summary>
```{r}
sessionInfo()
```
</details>
