---
title: "Seurat 5: Sketch integration"
output: html_notebook
---

```{r install_seurat, warning=FALSE, message=FALSE, eval=FALSE}
remotes::install_github("mojaveazure/seurat-object", ref = "feat/CalN_generic")
remotes::install_github("satijalab/seurat-private", ref = "feat/S5_transferAnchors")
```
 
## load library
```{r, warning=FALSE, message=FALSE}
library(Seurat)
library(BPCells)
library(Azimuth)
```
 
## load data from h5ad 
```{r, warning=FALSE, message=FALSE}
t0_CreateObject <- system.time({
  mat <- open_matrix_dir("/brahms/haoy/test/mouse_1M_neurons_counts") 
  options(Seurat.object.assay.version = "v5",  Seurat.object.assay.calcn = T)
  obj <- CreateSeuratObject(counts = mat )
})
```

## create sketch assay
```{r, warning=FALSE, message=FALSE}
t1_CreateSketchAssay <- system.time({
  obj <- NormalizeData(obj)
  obj <- FindVariableFeatures(obj, layer = 'counts')
  obj <- LeverageScore(obj)
  obj <- LeverageScoreSampling(object = obj, ncells = 50000, cast = 'dgCMatrix')
})
```
## Sketch assay clustering
```{r, warning=FALSE, message=FALSE}
t2_SketchClustering <- system.time({
  obj <- SCTransform(object = obj)
  obj <- RunPCA(obj)
  obj <- FindNeighbors(obj, dims = 1:30)
  obj <- FindClusters(obj, v)
})

obj <- RunUMAP(obj, dims = 1:30, return.model = T, verbose = F)
```

```{r}
DimPlot(obj, label = T, reduction = 'umap') + NoLegend() 
```

```{r}
options(Seurat.object.assay.version = "v3",  Seurat.object.assay.calcn = T)
obj.v3 <- CreateSeuratObject(counts =  as.sparse(obj[['sketch']]$counts) )

obj.v3 <- RunAzimuth(query = obj.v3, assay = 'RNA', reference = 'mousecortexref', do.adt = F) 

obj[['refAssay']] <- obj.v3[['refAssay']]
obj$predicted.subclass <- obj.v3$predicted.subclass
obj$predicted.cluster <- obj.v3$predicted.cluster
obj$predicted.subclass_smooth <- Seurat:::SmoothLabels(labels = obj$predicted.subclass , clusters = obj$SCT_snn_res.0.8  )
```

## Project full cells to PCA from sketch assay 
```{r, warning=FALSE, message=FALSE}
t3_ProjectEmbedding <- system.time({
  ref.emb <- ProjectCellEmbeddings(query = obj,
                                   reference = obj,
                                   query.assay = 'RNA', 
                                   reference.assay = 'SCT',
                                   normalization.method = 'SCT',
                                                reduction = 'pca')
obj[['pca.orig']] <- CreateDimReducObject(embeddings = ref.emb, assay = 'RNA')
DefaultAssay(obj) <- 'RNA'
})
``` 

## Transfer labels and umap from sketch to full data
```{r, warning=FALSE, message=FALSE}
t4_transferLabel <- system.time({
  obj <- TransferSketchLabels(object = obj,
                            atoms = 'sketch',
                            reduction = 'pca.orig',
                            dims = 1:30,
                            refdata = list(cluster_full = 'SCT_snn_res.0.8',
                                           subclass_full ='predicted.subclass'),
                            reduction.model = 'umap'
                            )
})
```


```{r}
library(ggplot2)
DimPlot(obj, label = T, reduction = 'ref.umap', group.by = 'predicted.cluster_full', alpha = 0.1) + NoLegend()  
DimPlot(obj, label = T, reduction = 'ref.umap', group.by = 'predicted.subclass_full', alpha = 0.1) + NoLegend()  
```

```{r}
all_T  <- ls(pattern = '^t')
overall <- sum(sapply(all_T, function(x) round(get(x)['elapsed'], digits = 3)))/60


for (i in 1:length(all_T)) {
  T_i <- get(all_T[i])['elapsed']
  if (T_i > 60) {
     print(paste(all_T[i], round(T_i/60, digits = 1), 'mins'))
  } else {
     print(paste(all_T[i], round(T_i, digits = 1), 'secs'))
  }
}
print(paste('Total time ', round(overall, digits = 3), 'mins' ))
```


```{r}
obj[['pca.nn']] <- Seurat:::NNHelper(data = obj[['pca.orig']]@cell.embeddings[,1:30], 
                            k = 30, 
                            method = "hnsw", 
                            metric = "cosine", 
                            n_threads = 10)
obj <- RunUMAP(obj, nn.name = "pca.nn", reduction.name = 'umap.orig', reduction.key = 'Uo_')

```

```{r}
DimPlot(obj, label = T, reduction = 'umap.orig', group.by = 'predicted.cluster_full', alpha = 0.1) + NoLegend()  
  DimPlot(obj, label = T, reduction = 'umap.orig', group.by = 'predicted.subclass_full', alpha = 0.1) + NoLegend()  
 
#saveRDS(obj, file = "/brahms/haoy/test/mouse_1M_neurons_seurat.rds")
```
