# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RunModularityClusteringCpp <- function(SNN, modularityFunction, resolution, algorithm, nRandomStarts, nIterations, randomSeed, printOutput, edgefilename = "", nThreads = 1L) {
    .Call('_Seurat_RunModularityClusteringCpp', PACKAGE = 'Seurat', SNN, modularityFunction, resolution, algorithm, nRandomStarts, nIterations, randomSeed, printOutput, edgefilename, nThreads)
}

RunModularityClusteringCpp_multi <- function(SNN, modularityFunction, resolutions, algorithm, nRandomStarts, nIterations, randomSeed, printOutput, edgefilename = "", nThreads = 1L) {
    .Call('_Seurat_RunModularityClusteringCpp_multi', PACKAGE = 'Seurat', SNN, modularityFunction, resolutions, algorithm, nRandomStarts, nIterations, randomSeed, printOutput, edgefilename, nThreads)
}

RunUMISampling <- function(data, sample_val, upsample = FALSE, display_progress = TRUE) {
    .Call('_Seurat_RunUMISampling', PACKAGE = 'Seurat', data, sample_val, upsample, display_progress)
}

RunUMISamplingPerCell <- function(data, sample_val, upsample = FALSE, display_progress = TRUE) {
    .Call('_Seurat_RunUMISamplingPerCell', PACKAGE = 'Seurat', data, sample_val, upsample, display_progress)
}

RowMergeMatrices <- function(mat1, mat2, mat1_rownames, mat2_rownames, all_rownames) {
    .Call('_Seurat_RowMergeMatrices', PACKAGE = 'Seurat', mat1, mat2, mat1_rownames, mat2_rownames, all_rownames)
}

LogNorm <- function(x, p, scale_factor, nthreads, display_progress) {
    .Call('_Seurat_LogNorm', PACKAGE = 'Seurat', x, p, scale_factor, nthreads, display_progress)
}

FindAllMarkersSparseFoldChangeStats <- function(x, i, p, rows, cols, groups, n_groups, log_normalize, nthreads = 1L) {
    .Call('_Seurat_FindAllMarkersSparseFoldChangeStats', PACKAGE = 'Seurat', x, i, p, rows, cols, groups, n_groups, log_normalize, nthreads)
}

Standardize <- function(mat, display_progress = TRUE) {
    .Call('_Seurat_Standardize', PACKAGE = 'Seurat', mat, display_progress)
}

FastSparseRowScale <- function(x, i, p, rows, cols, features = as.integer( c()), scale = TRUE, center = TRUE, scale_max = 10, nthreads = 1L, display_progress = FALSE) {
    .Call('_Seurat_FastSparseRowScale', PACKAGE = 'Seurat', x, i, p, rows, cols, features, scale, center, scale_max, nthreads, display_progress)
}

FastDenseRowScale <- function(mat, features = as.integer( c()), scale = TRUE, center = TRUE, scale_max = 10, nthreads = 1L, display_progress = FALSE) {
    .Call('_Seurat_FastDenseRowScale', PACKAGE = 'Seurat', mat, features, scale, center, scale_max, nthreads, display_progress)
}

FastSparseRowScaleWithKnownStats <- function(mat, mu, sigma, scale = TRUE, center = TRUE, scale_max = 10, display_progress = TRUE) {
    .Call('_Seurat_FastSparseRowScaleWithKnownStats', PACKAGE = 'Seurat', mat, mu, sigma, scale, center, scale_max, display_progress)
}

FastCov <- function(mat, center = TRUE) {
    .Call('_Seurat_FastCov', PACKAGE = 'Seurat', mat, center)
}

FastCovMats <- function(mat1, mat2, center = TRUE) {
    .Call('_Seurat_FastCovMats', PACKAGE = 'Seurat', mat1, mat2, center)
}

FastRBind <- function(mat1, mat2) {
    .Call('_Seurat_FastRBind', PACKAGE = 'Seurat', mat1, mat2)
}

FastExpMean <- function(mat, display_progress) {
    .Call('_Seurat_FastExpMean', PACKAGE = 'Seurat', mat, display_progress)
}

SparseRowMeanVar <- function(x, i, p, rows, cols, nthreads, display_progress) {
    .Call('_Seurat_SparseRowMeanVar', PACKAGE = 'Seurat', x, i, p, rows, cols, nthreads, display_progress)
}

SparseRowVarStd <- function(x, i, p, mu, sd, rows, cols, vmax, nthreads, display_progress) {
    .Call('_Seurat_SparseRowVarStd', PACKAGE = 'Seurat', x, i, p, mu, sd, rows, cols, vmax, nthreads, display_progress)
}

FastLogVMR <- function(mat, display_progress) {
    .Call('_Seurat_FastLogVMR', PACKAGE = 'Seurat', mat, display_progress)
}

RowVar <- function(x) {
    .Call('_Seurat_RowVar', PACKAGE = 'Seurat', x)
}

SparseRowMeanVarLegacy <- function(x, i, p, rows, cols, display_progress) {
    .Call('_Seurat_SparseRowMeanVarLegacy', PACKAGE = 'Seurat', x, i, p, rows, cols, display_progress)
}

SparseRowVarStdLegacyRows <- function(x, i, p, mu, sd, vmax, rows, cols, rows_use, nthreads, display_progress) {
    .Call('_Seurat_SparseRowVarStdLegacyRows', PACKAGE = 'Seurat', x, i, p, mu, sd, vmax, rows, cols, rows_use, nthreads, display_progress)
}

SparseRowVar <- function(mat, display_progress) {
    .Call('_Seurat_SparseRowVar', PACKAGE = 'Seurat', mat, display_progress)
}

ReplaceColsC <- function(mat, col_idx, replacement) {
    .Call('_Seurat_ReplaceColsC', PACKAGE = 'Seurat', mat, col_idx, replacement)
}

GraphToNeighborHelper <- function(mat) {
    .Call('_Seurat_GraphToNeighborHelper', PACKAGE = 'Seurat', mat)
}

fast_dist <- function(x, y, n) {
    .Call('_Seurat_fast_dist', PACKAGE = 'Seurat', x, y, n)
}

FindWeightsC <- function(cells2, distances, anchor_cells2, integration_matrix_rownames, cell_index, anchor_score, min_dist, sd, display_progress) {
    .Call('_Seurat_FindWeightsC', PACKAGE = 'Seurat', cells2, distances, anchor_cells2, integration_matrix_rownames, cell_index, anchor_score, min_dist, sd, display_progress)
}

IntegrateDataC <- function(integration_matrix, weights, expression_cells2) {
    .Call('_Seurat_IntegrateDataC', PACKAGE = 'Seurat', integration_matrix, weights, expression_cells2)
}

ScoreHelper <- function(snn, query_pca, query_dists, corrected_nns, k_snn, subtract_first_nn, display_progress) {
    .Call('_Seurat_ScoreHelper', PACKAGE = 'Seurat', snn, query_pca, query_dists, corrected_nns, k_snn, subtract_first_nn, display_progress)
}

EigenGramPCA <- function(object, npcs, weight_by_var, nthreads = 1L) {
    .Call('_Seurat_EigenGramPCA', PACKAGE = 'Seurat', object, npcs, weight_by_var, nthreads)
}

SCTResidualStatsAndCorrected <- function(x, i, p, rows, cols, theta, intercept, slope, log_umi, target_log_umi, min_var, residual_clip_min, residual_clip_max, n_threads = 1L, compute_corrected = TRUE) {
    .Call('_Seurat_SCTResidualStatsAndCorrected', PACKAGE = 'Seurat', x, i, p, rows, cols, theta, intercept, slope, log_umi, target_log_umi, min_var, residual_clip_min, residual_clip_max, n_threads, compute_corrected)
}

SCTPearsonResidualMatrix <- function(x, i, p, rows, cols, theta, intercept, slope, log_umi, feature_index, min_var, clip_min, clip_max, do_center = TRUE, n_threads = 1L) {
    .Call('_Seurat_SCTPearsonResidualMatrix', PACKAGE = 'Seurat', x, i, p, rows, cols, theta, intercept, slope, log_umi, feature_index, min_var, clip_min, clip_max, do_center, n_threads)
}

ComputeSNN <- function(nn_ranked, prune, nthreads) {
    .Call('_Seurat_ComputeSNN', PACKAGE = 'Seurat', nn_ranked, prune, nthreads)
}

SNN_SmallestNonzero_Dist <- function(snn, mat, n, nearest_dist) {
    .Call('_Seurat_SNN_SmallestNonzero_Dist', PACKAGE = 'Seurat', snn, mat, n, nearest_dist)
}

row_sum_dgcmatrix <- function(x, i, rows, cols) {
    .Call('_Seurat_row_sum_dgcmatrix', PACKAGE = 'Seurat', x, i, rows, cols)
}

row_mean_dgcmatrix <- function(x, i, rows, cols) {
    .Call('_Seurat_row_mean_dgcmatrix', PACKAGE = 'Seurat', x, i, rows, cols)
}

row_var_dgcmatrix <- function(x, i, rows, cols) {
    .Call('_Seurat_row_var_dgcmatrix', PACKAGE = 'Seurat', x, i, rows, cols)
}

