name: Reverse Dependency Checks

on:
  workflow_dispatch:

jobs:
  # Run a reverse dependency check similar to CRAN, for more details see 
  # https://github.com/r-devel/recheck.
  check-reverse-dependencies:
    uses: r-devel/recheck/.github/workflows/recheck.yml@v1
    with:
      which: all
